---
- name: add groups
  hosts: dev prod
  become: yes

  vars_files:
    - user_list.yml

  tasks:
    - name: add developer accounts
      group:
        name: "{{ item.group }}"
        state: present
      with_items: "{{ users }}"

- name: create user accounts 
  hosts: dev prod
  become: yes

  vars_files:
    - user_list.yml

  tasks:
    - name: add user accounts
      user:
        name: "{{ item.name }}"
        password: "{{ 'ablerate' | password_hash('sha512') }}"
        groups: "{{ item.group }}"
        append: yes
      with_items: "{{ users }}"
